name: pearson_flutter
description: A new Flutter application.

#remove
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  shared_preferences: ^0.5.12+4
  expandable: ^4.1.4
  dio: ^3.0.10
  provider: ^4.3.2+1
  sliding_up_panel:
  url_launcher: ^5.7.10
  fluentui_icons: ^0.2.0
  cached_network_image: ^2.3.3
  percent_indicator: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true


  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/syllabus/

  fonts:
    # Arquitecta
    - family: Arquitecta
      fonts:
        - asset: assets/fonts/arquiecta/Arquitecta_w400.ttf
        - asset: assets/fonts/arquiecta/Arquitecta_w400i.ttf
          style: italic
        - asset: assets/fonts/arquiecta/Arquitecta_w300.ttf
          weight: 300
        - asset: assets/fonts/arquiecta/Arquitecta_w700.ttf
          weight: 700
        - asset: assets/fonts/arquiecta/Arquitecta_w900.ttf
          weight: 900

    # Josefin Sans
    - family: Josefin Sans
      fonts:
        - asset: assets/fonts/josefin/JosefinSans_w100.ttf
          weight: 100
        - asset: assets/fonts/josefin/JosefinSans_w100i.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/josefin/JosefinSans_w200.ttf
          weight: 200
        - asset: assets/fonts/josefin/JosefinSans_w200i.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/josefin/JosefinSans_w300.ttf
          weight: 300
        - asset: assets/fonts/josefin/JosefinSans_w300i.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/josefin/JosefinSans_w400.ttf
        - asset: assets/fonts/josefin/JosefinSans_w400i.ttf
          style: italic
        - asset: assets/fonts/josefin/JosefinSans_w500.ttf
          weight: 500
        - asset: assets/fonts/josefin/JosefinSans_w500i.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/josefin/JosefinSans_w700.ttf
          weight: 700
        - asset: assets/fonts/josefin/JosefinSans_w700i.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/josefin/JosefinSans_w900.ttf
          weight: 900
        - asset: assets/fonts/josefin/JosefinSans_w900i.ttf
          weight: 900
          style: italic

    # Montserrat
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat_w100.ttf
          weight: 100
        - asset: assets/fonts/montserrat/Montserrat_w100i.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/montserrat/Montserrat_w200.ttf
          weight: 200
        - asset: assets/fonts/montserrat/Montserrat_w200i.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/montserrat/Montserrat_w300.ttf
          weight: 300
        - asset: assets/fonts/montserrat/Montserrat_w300i.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/montserrat/Montserrat_w400.ttf
        - asset: assets/fonts/montserrat/Montserrat_w400i.ttf
          style: italic
        - asset: assets/fonts/montserrat/Montserrat_w500.ttf
          weight: 500
        - asset: assets/fonts/montserrat/Montserrat_w500i.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/montserrat/Montserrat_w600.ttf
          weight: 600
        - asset: assets/fonts/montserrat/Montserrat_w600i.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/montserrat/Montserrat_w700.ttf
          weight: 700
        - asset: assets/fonts/montserrat/Montserrat_w700i.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/montserrat/Montserrat_w800.ttf
          weight: 800
        - asset: assets/fonts/montserrat/Montserrat_w800i.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/montserrat/Montserrat_w900.ttf
          weight: 900
        - asset: assets/fonts/montserrat/Montserrat_w900i.ttf
          weight: 900
          style: italic

    # Poppins
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins_w100.ttf
          weight: 100
        - asset: assets/fonts/poppins/Poppins_w100i.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/poppins/Poppins_w200.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins_w200i.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/poppins/Poppins_w300.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins_w300i.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/poppins/Poppins_w400.ttf
        - asset: assets/fonts/poppins/Poppins_w400i.ttf
          style: italic
        - asset: assets/fonts/poppins/Poppins_w500.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins_w500i.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/poppins/Poppins_w600.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins_w600i.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/poppins/Poppins_w700.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins_w700i.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/poppins/Poppins_w800.ttf
          weight: 800
        - asset: assets/fonts/poppins/Poppins_w800i.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/poppins/Poppins_w900.ttf
          weight: 900
        - asset: assets/fonts/poppins/Poppins_w900i.ttf
          weight: 900
          style: italic
